# Generated by Django 3.2.8 on 2021-11-11 15:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(default=None, max_length=255, verbose_name='Imdb ID')),
                ('title_type', models.CharField(choices=[], default='', max_length=255, verbose_name='Title Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_adult', models.BooleanField(default=False, verbose_name='Is Adult')),
                ('year', models.DateField(default='', verbose_name='Start Year')),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, verbose_name='Genres'), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(default='', max_length=255, verbose_name='Imdb ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('birth_year', models.DateField(verbose_name='Birth Year')),
                ('death_year', models.DateField(verbose_name='Death Year')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='ordering')),
                ('category', models.CharField(choices=[], max_length=255, verbose_name='category')),
                ('job', models.CharField(choices=[], max_length=255, verbose_name='job')),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, verbose_name='characters'), default=list, size=None)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tconst', to='movies.movie')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nconst', to='movies.person')),
            ],
        ),
    ]
