# Generated by Django 3.2.8 on 2021-11-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(default=None, verbose_name='Start Year'),
        ),
    ]
