# Generated by Django 3.2.8 on 2021-11-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211111_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmovie',
            name='order',
            field=models.IntegerField(null=True, verbose_name='ordering'),
        ),
    ]
