# Generated by Django 3.2.8 on 2021-11-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_personmovie_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmovie',
            name='movie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tconst', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nconst', to='movies.person'),
        ),
    ]
